db:
  host: localhost
  port: 3306
  database: skyblock
  user: skyblock
  password: skyblock
  pool-size: 10

main-world: world
join-message: true

islands:
  default-island:
    schematic: default_island.schematic # Default island schematic file
  y-coordinate: 100 # Y-coordinate for island spawn
  spacing: 512 # Spacing between islands in blocks