db:
  host: localhost
  port: 3306
  database: skyblock
  user: skyblock
  password: skyblock

islands:
  y-coordinate: 100 # Y-coordinate for island spawn
  spacing: 1000 # Spacing between islands in blocks