db:
  host: localhost
  port: 3306
  database: skyblock
  user: skyblock
  password: skyblock

main_world: world

islands:
  default-island:
    schematic: default_island.schematic # Default island schematic file
  y-coordinate: 100 # Y-coordinate for island spawn
  spacing: 1024 # Spacing between islands in blocks